tyd-client : ./src/dayrecord.c ./src/ipc_utils.c ./src/main.c ./src/record.c ./src/signal_utils.c ./src/utils.c ./src/window_manager.c ./src/x11_utils.c
	gcc -o tyd-client ./src/dayrecord.c ./src/ipc_utils.c ./src/main.c ./src/record.c ./src/signal_utils.c ./src/utils.c ./src/window_manager.c ./src/x11_utils.c -lpthread -lX11

